const fs = require('fs');
const path = require('path');

// Define the HTML content
const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Node.js Generated Page</title>
</head>
<body>
    <h1>Hello from Node.js!</h1>
    <p>This HTML file was generated by a Node.js application.</p>
</body>
</html>
`;

// Define the output path for index.html
const outputPath = path.join(__dirname, 'index.html');

// Write the HTML content to index.html
fs.writeFile(outputPath, htmlContent, (err) => {
    if (err) {
        console.error('Error writing to index.html:', err);
    } else {
        console.log('index.html file has been generated successfully!');
    }
});





